// Code generated by swaggo/swag. DO NOT EDIT.
// This file is a stub that is replaced when you run `make swagger`.
// Run `make swagger` to generate the real Swagger documentation.

package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds the exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Genset Monitoring API",
	Description:      "Production-ready IoT Genset Monitoring backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@genset-monitoring.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Returns the health status of the service and its infrastructure dependencies",
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "Service healthy",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "success": {"type": "boolean"},
                                "message": {"type": "string"},
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "postgres": {"type": "string"},
                                        "redis": {"type": "string"},
                                        "mqtt": {"type": "string"}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter the token with the Bearer: prefix",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
